export interface Product {
  id: string;
  name: string;
  category: "teas" | "herbs" | "spices" | "coffee" | "seeds" | "plants";
  subcategory?: string;
  price: number;
  description: string;
  keyPoints?: string;
  ingredients?: string;
  howToUse?: string;
  quality?: string;
  image?: string;
}

export const products: Product[] = [
  // Healing Teas - Our Innovations
  {
    id: "appetite-tea",
    name: "Appetite Tea",
    category: "teas",
    subcategory: "healing",
    price: 12.99,
    description: "A carefully crafted blend to help regulate appetite naturally.",
    keyPoints: "Supports healthy appetite regulation and digestive wellness.",
    ingredients: "Organic herbal blend with traditional African botanicals.",
    howToUse: "Steep one tea bag in hot water for 5-7 minutes. Enjoy before meals.",
  },
  {
    id: "arthritis-tea",
    name: "Arthritis Tea",
    category: "teas",
    subcategory: "healing",
    price: 14.99,
    description: "Natural blend designed to support joint health and comfort.",
    keyPoints: "Contains anti-inflammatory herbs to support joint mobility.",
    ingredients: "Turmeric, ginger, and traditional African herbs.",
    howToUse: "Steep for 5-7 minutes. Drink 2-3 cups daily for best results.",
  },
  {
    id: "bronchi-tea",
    name: "Bronchi Tea",
    category: "teas",
    subcategory: "healing",
    price: 13.99,
    description: "Respiratory support tea with eucalyptus and mint.",
    keyPoints: "Supports clear breathing and respiratory health.",
    ingredients: "Eucalyptus, peppermint, and soothing botanicals.",
    howToUse: "Steep in hot water for 5 minutes. Inhale steam before drinking.",
  },
  {
    id: "detox-tea",
    name: "Detox Tea",
    category: "teas",
    subcategory: "healing",
    price: 13.99,
    description: "Cleansing blend to support your body's natural detoxification.",
    keyPoints: "Supports liver function and natural cleansing processes.",
    ingredients: "Milk thistle, dandelion, and cleansing herbs.",
    howToUse: "Drink one cup in the morning on an empty stomach.",
  },
  {
    id: "diasure-tea",
    name: "DiaSure Tea",
    category: "teas",
    subcategory: "healing",
    price: 15.99,
    description: "Specially formulated to support healthy blood sugar levels.",
    keyPoints: "Contains herbs traditionally used for blood sugar support.",
    ingredients: "Bitter melon, fenugreek, and supporting botanicals.",
    howToUse: "Steep for 7 minutes. Drink before or after meals.",
  },
  {
    id: "femiguard-tea",
    name: "Femiguard Tea",
    category: "teas",
    subcategory: "healing",
    price: 14.99,
    description: "Women's wellness tea for hormonal balance support.",
    keyPoints: "Supports women's health and hormonal balance naturally.",
    ingredients: "Red clover, vitex, and nurturing botanicals.",
    howToUse: "Steep for 5-7 minutes. Enjoy 1-2 cups daily.",
  },
  {
    id: "hbp-tea",
    name: "HBP Tea",
    category: "teas",
    subcategory: "healing",
    price: 15.99,
    description: "Cardiovascular support tea for heart health.",
    keyPoints: "Contains herbs that support healthy blood pressure.",
    ingredients: "Hibiscus, hawthorn, and heart-supporting herbs.",
    howToUse: "Steep for 5-7 minutes. Drink 2-3 cups daily.",
  },
  {
    id: "liver-lubie-tea",
    name: "Liver Lubie Tea",
    category: "teas",
    subcategory: "healing",
    price: 14.99,
    description: "Liver support tea with milk thistle and protective herbs.",
    keyPoints: "Supports liver health and natural detoxification.",
    ingredients: "Milk thistle, artichoke, and liver-supporting botanicals.",
    howToUse: "Steep for 7 minutes. Best enjoyed in the morning.",
  },
  {
    id: "prostasure-tea",
    name: "Prostasure Tea",
    category: "teas",
    subcategory: "healing",
    price: 15.99,
    description: "Men's health tea for prostate wellness support.",
    keyPoints: "Contains herbs traditionally used for prostate health.",
    ingredients: "Saw palmetto, nettle root, and supporting herbs.",
    howToUse: "Steep for 5-7 minutes. Drink 2 cups daily.",
  },
  {
    id: "stress-free-tea",
    name: "Stress Free Tea",
    category: "teas",
    subcategory: "healing",
    price: 12.99,
    description: "Calming blend to help you unwind and relax.",
    keyPoints: "Promotes relaxation and supports stress management.",
    ingredients: "Chamomile, lavender, and calming botanicals.",
    howToUse: "Steep for 5 minutes. Enjoy before bed or during stressful times.",
  },
  {
    id: "supper-detox-tea",
    name: "Supper Detox Tea",
    category: "teas",
    subcategory: "healing",
    price: 13.99,
    description: "Evening cleansing tea for overnight detoxification.",
    keyPoints: "Supports overnight cleansing and morning freshness.",
    ingredients: "Senna, peppermint, and gentle cleansing herbs.",
    howToUse: "Drink one cup after dinner, before bed.",
  },
  {
    id: "ulcerine-tea",
    name: "Ulcerine Tea",
    category: "teas",
    subcategory: "healing",
    price: 14.99,
    description: "Soothing tea for digestive comfort and stomach wellness.",
    keyPoints: "Supports stomach lining health and digestive comfort.",
    ingredients: "Licorice root, slippery elm, and soothing herbs.",
    howToUse: "Steep for 7 minutes. Drink between meals.",
  },

  // Green Teas
  {
    id: "black-tea",
    name: "Black Tea",
    category: "teas",
    subcategory: "green",
    price: 9.99,
    description: "Classic black tea with rich, robust flavor.",
    keyPoints: "Rich in antioxidants and provides natural energy.",
    ingredients: "Organic Camellia sinensis leaves.",
    howToUse: "Steep in boiling water for 3-5 minutes.",
  },
  {
    id: "green-tea",
    name: "Green Tea",
    category: "teas",
    subcategory: "green",
    price: 9.99,
    description: "Pure green tea with delicate, refreshing taste.",
    keyPoints: "High in catechins and antioxidants for wellness.",
    ingredients: "Organic green tea leaves.",
    howToUse: "Steep in 80°C water for 2-3 minutes.",
  },
  {
    id: "oolong-tea",
    name: "Oolong Tea",
    category: "teas",
    subcategory: "green",
    price: 11.99,
    description: "Semi-oxidized tea with complex, floral notes.",
    keyPoints: "Combines benefits of green and black tea.",
    ingredients: "Premium oolong tea leaves.",
    howToUse: "Steep in 90°C water for 3-5 minutes.",
  },
  {
    id: "purple-tea",
    name: "Purple Tea",
    category: "teas",
    subcategory: "green",
    price: 12.99,
    description: "Rich in antioxidants. It contains high levels of anthocyanins and polyphenols which reduce oxidative stress.",
    keyPoints: "Excellent for boosting metabolism, supporting weight management, reducing inflammation, and promoting cardiovascular health.",
    ingredients: "Organic Camellia sinensis plant.",
    howToUse: "Steep one tea bag in hot water for 5-7 minutes. Can be enjoyed hot or cold.",
    quality: "Premium quality purple tea grown at high altitude in Kenya.",
  },
  {
    id: "spiced-tea",
    name: "Spiced Tea",
    category: "teas",
    subcategory: "green",
    price: 10.99,
    description: "Warming spiced tea blend with cinnamon and ginger.",
    keyPoints: "Warming blend perfect for cold days.",
    ingredients: "Black tea, cinnamon, ginger, cardamom.",
    howToUse: "Steep in boiling water for 4-5 minutes.",
  },
  {
    id: "yellow-tea",
    name: "Yellow Tea",
    category: "teas",
    subcategory: "green",
    price: 13.99,
    description: "Rare yellow tea with smooth, mellow flavor.",
    keyPoints: "Gently processed for a smooth, mellow taste.",
    ingredients: "Premium yellow tea leaves.",
    howToUse: "Steep in 75°C water for 2-3 minutes.",
  },
  {
    id: "early-grey-tea",
    name: "Early Grey",
    category: "teas",
    subcategory: "green",
    price: 10.99,
    description: "Classic Earl Grey with bergamot citrus notes.",
    keyPoints: "Aromatic blend with natural bergamot oil.",
    ingredients: "Black tea, natural bergamot flavor.",
    howToUse: "Steep in boiling water for 3-4 minutes.",
  },

  // Green Tea Varietals
  {
    id: "alfalfa-tea",
    name: "Alfalfa Tea",
    category: "teas",
    subcategory: "green-varietals",
    price: 11.99,
    description: "Nutrient-rich alfalfa tea for overall wellness.",
    keyPoints: "Rich in vitamins and minerals.",
    ingredients: "Organic alfalfa leaves.",
    howToUse: "Steep for 5-7 minutes.",
  },
  {
    id: "avocado-tea",
    name: "Avocado Tea",
    category: "teas",
    subcategory: "green-varietals",
    price: 12.99,
    description: "Made from avocado leaves, known for health benefits.",
    keyPoints: "Supports cardiovascular health.",
    ingredients: "Organic avocado leaves.",
    howToUse: "Steep for 5-7 minutes.",
  },
  {
    id: "blackberry-tea",
    name: "Blackberry Tea",
    category: "teas",
    subcategory: "green-varietals",
    price: 11.99,
    description: "Rich in vitamins and strengthens the immune membrane of the digestive tract.",
    keyPoints: "High in antioxidants and vitamin C.",
    ingredients: "Organic blackberry leaves and fruit.",
    howToUse: "Steep for 5 minutes. Enjoy hot or iced.",
  },
  {
    id: "sage-tea",
    name: "Sage Tea",
    category: "teas",
    subcategory: "green-varietals",
    price: 10.99,
    description: "Traditional sage tea with earthy, aromatic flavor.",
    keyPoints: "Supports memory and cognitive function.",
    ingredients: "Organic sage leaves.",
    howToUse: "Steep for 5 minutes.",
  },
  {
    id: "turmeric-tea",
    name: "Turmeric Tea",
    category: "teas",
    subcategory: "green-varietals",
    price: 12.99,
    description: "Rich in curcumin. A warm cup before bedtime helps the body wind down and relax.",
    keyPoints: "Powerful anti-inflammatory and antioxidant properties.",
    ingredients: "Organic turmeric root, black pepper.",
    howToUse: "Steep for 7 minutes. Add honey to taste.",
  },
  {
    id: "centella-tea",
    name: "Centella Tea",
    category: "teas",
    subcategory: "green-varietals",
    price: 13.99,
    description: "Also known as Gotu Kola, supports brain health.",
    keyPoints: "Traditional herb for cognitive support.",
    ingredients: "Organic centella asiatica.",
    howToUse: "Steep for 5-7 minutes.",
  },
  {
    id: "chamomile-tea",
    name: "Chamomile Tea",
    category: "teas",
    subcategory: "green-varietals",
    price: 9.99,
    description: "Calming chamomile flowers for relaxation.",
    keyPoints: "Promotes restful sleep and relaxation.",
    ingredients: "Organic chamomile flowers.",
    howToUse: "Steep for 5 minutes before bed.",
  },
  {
    id: "geranium-tea",
    name: "Geranium Tea",
    category: "teas",
    subcategory: "green-varietals",
    price: 11.99,
    description: "Aromatic geranium leaf tea with floral notes.",
    keyPoints: "Supports emotional balance.",
    ingredients: "Organic scented geranium leaves.",
    howToUse: "Steep for 5 minutes.",
  },
  {
    id: "lavender-tea",
    name: "Lavender Tea",
    category: "teas",
    subcategory: "green-varietals",
    price: 11.99,
    description: "Soothing lavender flower tea for relaxation.",
    keyPoints: "Calming aroma promotes relaxation.",
    ingredients: "Organic lavender flowers.",
    howToUse: "Steep for 5 minutes. Perfect for evening.",
  },
  {
    id: "raspberry-tea",
    name: "Raspberry Tea",
    category: "teas",
    subcategory: "green-varietals",
    price: 10.99,
    description: "Fruity raspberry leaf tea with sweet notes.",
    keyPoints: "Rich in nutrients, supports women's health.",
    ingredients: "Organic raspberry leaves.",
    howToUse: "Steep for 5-7 minutes.",
  },
  {
    id: "stinging-nettle-tea",
    name: "Stinging Nettle Tea",
    category: "teas",
    subcategory: "green-varietals",
    price: 10.99,
    description: "Mineral-rich nettle tea for overall wellness.",
    keyPoints: "High in iron and supports joint health.",
    ingredients: "Organic stinging nettle leaves.",
    howToUse: "Steep for 5-7 minutes.",
  },
  {
    id: "chayote-tea",
    name: "Chayote Tea",
    category: "teas",
    subcategory: "green-varietals",
    price: 11.99,
    description: "Made from chayote plant for blood sugar support.",
    keyPoints: "Traditional remedy for blood sugar balance.",
    ingredients: "Organic chayote leaves.",
    howToUse: "Steep for 7 minutes.",
  },
  {
    id: "eucalyptus-tea",
    name: "Eucalyptus Tea",
    category: "teas",
    subcategory: "green-varietals",
    price: 10.99,
    description: "Refreshing eucalyptus for respiratory support.",
    keyPoints: "Supports clear breathing and respiratory health.",
    ingredients: "Organic eucalyptus leaves.",
    howToUse: "Steep for 5 minutes. Inhale the steam.",
  },
  {
    id: "guava-tea",
    name: "Guava Tea",
    category: "teas",
    subcategory: "green-varietals",
    price: 10.99,
    description: "Tropical guava leaf tea with health benefits.",
    keyPoints: "Supports digestive health and blood sugar.",
    ingredients: "Organic guava leaves.",
    howToUse: "Steep for 5-7 minutes.",
  },
  {
    id: "loquat-tea",
    name: "Loquat Tea",
    category: "teas",
    subcategory: "green-varietals",
    price: 11.99,
    description: "Traditional loquat leaf tea for respiratory health.",
    keyPoints: "Soothes the throat and supports breathing.",
    ingredients: "Organic loquat leaves.",
    howToUse: "Steep for 7 minutes.",
  },
  {
    id: "red-clover-tea",
    name: "Red Clover Tea",
    category: "teas",
    subcategory: "green-varietals",
    price: 11.99,
    description: "Floral red clover tea for women's wellness.",
    keyPoints: "Supports hormonal balance and skin health.",
    ingredients: "Organic red clover blossoms.",
    howToUse: "Steep for 5-7 minutes.",
  },
  {
    id: "soursop-tea",
    name: "Soursop Tea",
    category: "teas",
    subcategory: "green-varietals",
    price: 13.99,
    description: "Tropical soursop leaf tea with powerful benefits.",
    keyPoints: "Rich in antioxidants and immune support.",
    ingredients: "Organic soursop leaves.",
    howToUse: "Steep for 7-10 minutes.",
  },
  {
    id: "dandelion-tea",
    name: "Dandelion Tea",
    category: "teas",
    subcategory: "green-varietals",
    price: 9.99,
    description: "Cleansing dandelion root tea for liver support.",
    keyPoints: "Supports liver health and digestion.",
    ingredients: "Organic dandelion root.",
    howToUse: "Steep for 7 minutes.",
  },
  {
    id: "primrose-tea",
    name: "E/Primrose Tea",
    category: "teas",
    subcategory: "green-varietals",
    price: 12.99,
    description: "Evening primrose tea for skin and hormonal health.",
    keyPoints: "Supports skin health and hormonal balance.",
    ingredients: "Organic evening primrose.",
    howToUse: "Steep for 5-7 minutes.",
  },
  {
    id: "mango-tea",
    name: "Mango Tea",
    category: "teas",
    subcategory: "green-varietals",
    price: 10.99,
    description: "Tropical mango leaf tea with sweet notes.",
    keyPoints: "Supports blood sugar balance.",
    ingredients: "Organic mango leaves.",
    howToUse: "Steep for 5 minutes.",
  },
  {
    id: "milk-thistle-tea",
    name: "Milk Thistle Tea",
    category: "teas",
    subcategory: "green-varietals",
    price: 12.99,
    description: "Liver-protective milk thistle tea.",
    keyPoints: "Contains silymarin for liver protection.",
    ingredients: "Organic milk thistle seeds.",
    howToUse: "Steep for 7-10 minutes.",
  },
  {
    id: "feverfew-tea",
    name: "Feverfew Tea",
    category: "teas",
    subcategory: "green-varietals",
    price: 11.99,
    description: "Traditional feverfew for headache support.",
    keyPoints: "Traditional remedy for headaches.",
    ingredients: "Organic feverfew leaves.",
    howToUse: "Steep for 5-7 minutes.",
  },

  // Culinary Herbs
  {
    id: "capsicum",
    name: "Capsicum",
    category: "herbs",
    price: 6.99,
    description: "Fresh dried capsicum peppers for cooking.",
  },
  {
    id: "chilli",
    name: "Chilli",
    category: "herbs",
    price: 5.99,
    description: "Dried chilli peppers with perfect heat.",
  },
  {
    id: "chives",
    name: "Chives",
    category: "herbs",
    price: 4.99,
    description: "Fresh dried chives for garnishing and cooking.",
  },
  {
    id: "goose-mint",
    name: "Goose Mint",
    category: "herbs",
    price: 5.99,
    description: "Aromatic goose mint for culinary use.",
  },
  {
    id: "leeks",
    name: "Leeks",
    category: "herbs",
    price: 5.99,
    description: "Dried leeks for soups and stews.",
  },
  {
    id: "melisa",
    name: "Melisa",
    category: "herbs",
    price: 6.99,
    description: "Lemon balm herb with citrus notes.",
  },
  {
    id: "moringa",
    name: "Moringa",
    category: "herbs",
    price: 8.99,
    description: "Nutrient-dense moringa leaf powder.",
  },
  {
    id: "oregano",
    name: "Oregano",
    category: "herbs",
    price: 5.99,
    description: "Classic oregano for Italian and Mediterranean dishes.",
  },
  {
    id: "peppermint",
    name: "Pepper Mint",
    category: "herbs",
    price: 5.99,
    description: "Refreshing peppermint for teas and cooking.",
  },
  {
    id: "rosemary",
    name: "Rosemary",
    category: "herbs",
    price: 5.99,
    description: "Aromatic rosemary for roasts and Mediterranean cuisine.",
  },
  {
    id: "sage",
    name: "Sage",
    category: "herbs",
    price: 5.99,
    description: "Earthy sage for savory dishes.",
  },
  {
    id: "savory",
    name: "Savory",
    category: "herbs",
    price: 5.99,
    description: "Peppery savory herb for beans and meat.",
  },
  {
    id: "stinging-nettle-herb",
    name: "Stinging Nettle",
    category: "herbs",
    price: 6.99,
    description: "Dried stinging nettle for cooking and teas.",
  },
  {
    id: "tarragon",
    name: "Tarragon",
    category: "herbs",
    price: 6.99,
    description: "Anise-flavored tarragon for French cuisine.",
  },
  {
    id: "thyme",
    name: "Thyme",
    category: "herbs",
    price: 5.99,
    description: "Versatile thyme for all types of cooking.",
  },
  {
    id: "coffee-herb",
    name: "Coffee",
    category: "herbs",
    price: 9.99,
    description: "Premium coffee beans and grounds.",
  },

  // Spices
  {
    id: "cardamoms",
    name: "Cardamoms",
    category: "spices",
    price: 8.99,
    description: "Aromatic cardamom pods for sweet and savory dishes.",
  },
  {
    id: "cinnamon",
    name: "Cinnamon",
    category: "spices",
    price: 6.99,
    description: "Sweet Ceylon cinnamon sticks and powder.",
  },
  {
    id: "cloves",
    name: "Cloves",
    category: "spices",
    price: 7.99,
    description: "Whole cloves for warming spice blends.",
  },
  {
    id: "cummin-seeds",
    name: "Cummin Seeds",
    category: "spices",
    price: 5.99,
    description: "Earthy cumin seeds for curries and Middle Eastern dishes.",
  },
  {
    id: "dill-seeds",
    name: "Dill Seeds",
    category: "spices",
    price: 5.99,
    description: "Aromatic dill seeds for pickling and cooking.",
  },
  {
    id: "fennel-seeds",
    name: "Fennel Seeds",
    category: "spices",
    price: 5.99,
    description: "Sweet fennel seeds for digestive support.",
  },
  {
    id: "fenugreek",
    name: "Fenugreek",
    category: "spices",
    price: 5.99,
    description: "Bitter-sweet fenugreek seeds for curries.",
  },
  {
    id: "ginger",
    name: "Ginger",
    category: "spices",
    price: 6.99,
    description: "Warming dried ginger for teas and cooking.",
  },

  // Seasonings
  {
    id: "chili-powder",
    name: "Chili Powder",
    category: "spices",
    subcategory: "seasoning",
    price: 5.99,
    description: "Ground chili powder for adding heat.",
  },
  {
    id: "chilli-seasoning",
    name: "Chilli Seasoning",
    category: "spices",
    subcategory: "seasoning",
    price: 6.99,
    description: "Blended chilli seasoning mix.",
  },
  {
    id: "lemon-seasoning",
    name: "Lemon Seasoning",
    category: "spices",
    subcategory: "seasoning",
    price: 6.99,
    description: "Zesty lemon seasoning for fish and poultry.",
  },
  {
    id: "meat-seasoning",
    name: "Meat Seasoning",
    category: "spices",
    subcategory: "seasoning",
    price: 7.99,
    description: "Perfect blend for all types of meat.",
  },
  {
    id: "soup-mix",
    name: "Soup Mix",
    category: "spices",
    subcategory: "seasoning",
    price: 6.99,
    description: "Hearty soup seasoning mix.",
  },

  // Coffee
  {
    id: "green-coffee",
    name: "Green Coffee",
    category: "coffee",
    price: 12.99,
    description: "Unroasted green coffee beans for home roasting.",
  },
  {
    id: "parchment-coffee",
    name: "Parchment Coffee",
    category: "coffee",
    price: 11.99,
    description: "Coffee in parchment for extended freshness.",
  },
  {
    id: "mild-roast",
    name: "Mild Roast",
    category: "coffee",
    price: 13.99,
    description: "Light, mild roast coffee beans.",
  },
  {
    id: "medium-roast",
    name: "Medium Roast",
    category: "coffee",
    price: 13.99,
    description: "Balanced medium roast coffee.",
  },
  {
    id: "hard-roast",
    name: "Hard Roast",
    category: "coffee",
    price: 14.99,
    description: "Bold, dark roast coffee beans.",
  },

  // Seeds
  {
    id: "herb-seeds",
    name: "Herb Seeds Collection",
    category: "seeds",
    price: 8.99,
    description: "Assorted medicinal herb seeds for home growing.",
  },
  {
    id: "vegetable-seeds",
    name: "Vegetable Seeds",
    category: "seeds",
    price: 7.99,
    description: "Organic vegetable seeds for your garden.",
  },

  // Plants
  {
    id: "mint-plant",
    name: "Mint",
    category: "plants",
    price: 9.99,
    description: "Fresh mint plant for your herb garden.",
  },
  {
    id: "rosemary-plant",
    name: "Rosemary",
    category: "plants",
    price: 11.99,
    description: "Hardy rosemary plant for cooking and aromatherapy.",
  },
  {
    id: "spearmint-plant",
    name: "Spearmint",
    category: "plants",
    price: 9.99,
    description: "Sweet spearmint plant for teas and cooking.",
  },
];

export const medicinalPlants = [
  "Ajuga Remota",
  "Artemisia annua",
  "Avocado",
  "California Poppy",
  "Celery",
  "Chamomile",
  "Chayote",
  "Cilantro",
  "Comfrey",
  "Dill seeds",
  "Eucalyptus",
  "Fennel seeds",
  "Fenugreek",
  "Feverfew",
  "Goose mint",
  "Lancelot Minor",
  "Lavender",
  "Lemon grass",
  "Loquart",
  "Madagascan Periwinkle",
  "Melisa",
  "Mexican bush sage",
  "Milk Thistle",
  "Muigoya",
  "Oregano",
  "Ox eye daisy",
  "Parsley",
  "Passion fruit",
  "Pepper mint",
  "Plantago Major",
  "Plantago minor",
  "Prunus Africana",
  "Rosemary",
  "Sage salvia",
  "Scented-Leaf Geraniums",
  "Spearmint",
  "Stinging nettle",
  "Thyme",
  "Warburgia UG",
];

export function getProductsByCategory(category: string) {
  if (category === "all") return products;
  return products.filter((p) => p.category === category);
}

export function getProductById(id: string) {
  return products.find((p) => p.id === id);
}
