export type ProductCategory =
  | "all"
  | "healing-teas"
  | "green-teas"
  | "culinary-herbs"
  | "spices"
  | "coffee"
  | "seeds"
  | "seasonings"

export interface Product {
  id: string
  name: string
  price: number
  category: ProductCategory
  image: string
  description: string
  ingredients?: string
  keyPoints?: string[]
  howToUse?: string
}

export const products: Product[] = [
  // Healing Teas
  {
    id: "appetite-tea",
    name: "Appetite Tea",
    price: 12.99,
    category: "healing-teas",
    image: "https://images.unsplash.com/photo-1544787219-7f47ccb76574?w=400&q=80",
    description: "A carefully blended herbal tea designed to naturally stimulate appetite and support healthy digestion. Perfect for those needing to restore their natural hunger cues.",
    ingredients: "Chamomile, Ginger root, Fennel seeds, Lemon balm",
    keyPoints: ["Stimulates natural appetite", "Supports digestive health", "Calming properties"],
    howToUse: "Steep one tea bag in hot water for 5-7 minutes. Drink 30 minutes before meals.",
  },
  {
    id: "arthritis-tea",
    name: "Arthritis Tea",
    price: 14.99,
    category: "healing-teas",
    image: "https://images.unsplash.com/photo-1563822249366-3efb23b8e0c9?w=400&q=80",
    description: "Anti-inflammatory blend to help soothe joint pain and improve mobility. Made with traditional African herbs known for their healing properties.",
    ingredients: "Turmeric, Ginger, Stinging nettle, Willow bark",
    keyPoints: ["Reduces inflammation", "Supports joint health", "Natural pain relief"],
    howToUse: "Drink 2-3 cups daily for best results.",
  },
  {
    id: "bronchi-tea",
    name: "Bronchi Tea",
    price: 13.99,
    category: "healing-teas",
    image: "https://images.unsplash.com/photo-1597318181409-cf64d0b5d8a2?w=400&q=80",
    description: "Respiratory support tea to help clear airways and ease breathing. Formulated with eucalyptus and other soothing herbs.",
    ingredients: "Eucalyptus, Thyme, Mullein, Licorice root",
    keyPoints: ["Clears airways", "Soothes respiratory tract", "Supports lung health"],
    howToUse: "Inhale the steam while drinking for maximum benefit.",
  },
  {
    id: "detox-tea",
    name: "Detox Tea",
    price: 13.99,
    category: "healing-teas",
    image: "https://images.unsplash.com/photo-1556679343-c7306c1976bc?w=400&q=80",
    description: "A cleansing blend to support your body's natural detoxification processes. Helps flush toxins and promote overall wellness.",
    ingredients: "Dandelion root, Milk thistle, Burdock, Green tea",
    keyPoints: ["Supports liver function", "Promotes cleansing", "Boosts metabolism"],
    howToUse: "Drink first thing in the morning on an empty stomach.",
  },
  {
    id: "diasure-tea",
    name: "DiaSure Tea",
    price: 15.99,
    category: "healing-teas",
    image: "https://images.unsplash.com/photo-1571934811356-5cc061b6821f?w=400&q=80",
    description: "Specially formulated to help maintain healthy blood sugar levels. A natural approach to diabetes management support.",
    ingredients: "Bitter melon, Fenugreek, Cinnamon, Gymnema",
    keyPoints: ["Supports blood sugar balance", "Natural ingredients", "Daily wellness support"],
    howToUse: "Drink after meals, 2-3 times daily.",
  },
  {
    id: "femiguard-tea",
    name: "Femiguard Tea",
    price: 14.99,
    category: "healing-teas",
    image: "https://images.unsplash.com/photo-1564890369478-c89ca6d9cde9?w=400&q=80",
    description: "Women's health tea blend supporting hormonal balance and reproductive wellness. Gentle yet effective formula.",
    ingredients: "Red raspberry leaf, Vitex, Dong quai, Chamomile",
    keyPoints: ["Hormonal balance", "Reproductive health", "Menstrual comfort"],
    howToUse: "Drink 1-2 cups daily throughout menstrual cycle.",
  },
  {
    id: "hbp-tea",
    name: "HBP Tea",
    price: 15.99,
    category: "healing-teas",
    image: "https://images.unsplash.com/photo-1558160074-4d7d8bdf4256?w=400&q=80",
    description: "Heart-healthy blend to support healthy blood pressure levels. Made with herbs traditionally used for cardiovascular wellness.",
    ingredients: "Hibiscus, Hawthorn, Olive leaf, Garlic",
    keyPoints: ["Supports healthy blood pressure", "Cardiovascular health", "Antioxidant rich"],
    howToUse: "Drink 2 cups daily, morning and evening.",
  },
  {
    id: "liver-lubie-tea",
    name: "Liver Lubie Tea",
    price: 14.99,
    category: "healing-teas",
    image: "https://images.unsplash.com/photo-1576092768241-dec231879fc3?w=400&q=80",
    description: "Liver support and cleansing tea to promote optimal liver function and detoxification.",
    ingredients: "Milk thistle, Dandelion, Artichoke, Turmeric",
    keyPoints: ["Liver protection", "Detoxification support", "Digestive aid"],
    howToUse: "Best consumed before bedtime for overnight cleansing.",
  },
  {
    id: "prostasure-tea",
    name: "Prostasure Tea",
    price: 15.99,
    category: "healing-teas",
    image: "https://images.unsplash.com/photo-1594631252845-29fc4cc8cde9?w=400&q=80",
    description: "Men's health formula supporting prostate wellness. Natural herbs for urinary and reproductive health.",
    ingredients: "Saw palmetto, Nettle root, Pygeum, Pumpkin seed",
    keyPoints: ["Prostate health", "Urinary support", "Men's wellness"],
    howToUse: "Drink 2 cups daily for optimal results.",
  },
  {
    id: "stress-free-tea",
    name: "Stress Free Tea",
    price: 12.99,
    category: "healing-teas",
    image: "https://images.unsplash.com/photo-1544787219-7f47ccb76574?w=400&q=80",
    description: "Calming blend to help reduce stress and anxiety. Perfect for unwinding after a long day.",
    ingredients: "Lavender, Chamomile, Lemon balm, Passionflower",
    keyPoints: ["Stress relief", "Promotes relaxation", "Better sleep"],
    howToUse: "Enjoy in the evening or during stressful moments.",
  },
  {
    id: "supper-detox-tea",
    name: "Supper Detox Tea",
    price: 14.99,
    category: "healing-teas",
    image: "https://images.unsplash.com/photo-1556679343-c7306c1976bc?w=400&q=80",
    description: "Deep cleansing tea for comprehensive detoxification. Supports multiple organ systems.",
    ingredients: "Senna, Cascara, Ginger, Peppermint",
    keyPoints: ["Deep cleansing", "Gentle elimination", "Digestive reset"],
    howToUse: "Drink before bed, not recommended for daily use.",
  },
  {
    id: "ulcerine-tea",
    name: "Ulcerine Tea",
    price: 15.99,
    category: "healing-teas",
    image: "https://images.unsplash.com/photo-1597318181409-cf64d0b5d8a2?w=400&q=80",
    description: "Soothing blend for digestive comfort. Helps calm and protect the stomach lining.",
    ingredients: "Licorice root, Slippery elm, Marshmallow root, Aloe",
    keyPoints: ["Stomach soothing", "Protective coating", "Digestive comfort"],
    howToUse: "Drink 20 minutes before meals.",
  },

  // Green Teas
  {
    id: "black-tea",
    name: "Black Tea",
    price: 10.99,
    category: "green-teas",
    image: "https://images.unsplash.com/photo-1576092768241-dec231879fc3?w=400&q=80",
    description: "Premium black tea with rich, robust flavor. Full-bodied and perfect for any time of day.",
    ingredients: "Organic Camellia sinensis leaves",
    keyPoints: ["Rich flavor", "Natural energy", "Antioxidant properties"],
    howToUse: "Steep 3-5 minutes in boiling water.",
  },
  {
    id: "green-tea",
    name: "Green Tea",
    price: 11.99,
    category: "green-teas",
    image: "https://images.unsplash.com/photo-1556679343-c7306c1976bc?w=400&q=80",
    description: "Classic green tea with delicate flavor and numerous health benefits. Lightly caffeinated.",
    ingredients: "Organic green tea leaves",
    keyPoints: ["Metabolism boost", "Antioxidant rich", "Mental clarity"],
    howToUse: "Steep 2-3 minutes in water just below boiling.",
  },
  {
    id: "oolong-tea",
    name: "Oolong Tea",
    price: 12.99,
    category: "green-teas",
    image: "https://images.unsplash.com/photo-1564890369478-c89ca6d9cde9?w=400&q=80",
    description: "Semi-oxidized tea with complex, nuanced flavor. Between green and black tea.",
    ingredients: "Premium oolong tea leaves",
    keyPoints: ["Unique flavor profile", "Digestive support", "Moderate caffeine"],
    howToUse: "Multiple infusions recommended, increasing steep time.",
  },
  {
    id: "purple-tea",
    name: "Purple Tea",
    price: 14.99,
    category: "green-teas",
    image: "https://images.unsplash.com/photo-1544787219-7f47ccb76574?w=400&q=80",
    description: "Rich in antioxidants. It contains high levels of anthocyanins and polyphenols which reduce oxidative stress.",
    ingredients: "Organic Camellia sinensis (purple variety)",
    keyPoints: ["High in anthocyanins", "Reduces oxidative stress", "Weight management support"],
    howToUse: "Steep 3-4 minutes in hot water.",
  },
  {
    id: "spiced-tea",
    name: "Spiced Tea",
    price: 11.99,
    category: "green-teas",
    image: "https://images.unsplash.com/photo-1571934811356-5cc061b6821f?w=400&q=80",
    description: "Warming blend of tea and aromatic spices. Perfect for cold weather.",
    ingredients: "Black tea, Cinnamon, Cardamom, Ginger, Cloves",
    keyPoints: ["Warming", "Digestive aid", "Immune support"],
    howToUse: "Steep 5 minutes, add milk if desired.",
  },
  {
    id: "yellow-tea",
    name: "Yellow Tea",
    price: 15.99,
    category: "green-teas",
    image: "https://images.unsplash.com/photo-1558160074-4d7d8bdf4256?w=400&q=80",
    description: "Rare and delicate tea with mellow, sweet flavor. A true connoisseur's choice.",
    ingredients: "Yellow tea leaves",
    keyPoints: ["Rare variety", "Gentle on stomach", "Subtle sweetness"],
    howToUse: "Steep 2-3 minutes in water at 75-80°C.",
  },
  {
    id: "early-grey",
    name: "Early Grey",
    price: 11.99,
    category: "green-teas",
    image: "https://images.unsplash.com/photo-1594631252845-29fc4cc8cde9?w=400&q=80",
    description: "Classic Earl Grey with bergamot citrus notes. Elegant and aromatic.",
    ingredients: "Black tea, Natural bergamot oil",
    keyPoints: ["Citrus aroma", "Classic flavor", "Uplifting"],
    howToUse: "Steep 3-5 minutes, enjoy plain or with milk.",
  },

  // Culinary Herbs
  {
    id: "capsicum",
    name: "Capsicum",
    price: 6.99,
    category: "culinary-herbs",
    image: "https://images.unsplash.com/photo-1563565375-f3fdfdbefa83?w=400&q=80",
    description: "Dried capsicum peppers for adding heat and flavor to dishes. Rich in vitamins.",
    ingredients: "100% dried capsicum",
    keyPoints: ["Adds heat", "Rich in vitamin C", "Metabolism boost"],
  },
  {
    id: "chilli",
    name: "Chilli",
    price: 5.99,
    category: "culinary-herbs",
    image: "https://images.unsplash.com/photo-1583119022894-919a68a3d0e3?w=400&q=80",
    description: "Fiery dried chillis to spice up any cuisine. Organically grown.",
    ingredients: "100% organic dried chilli",
    keyPoints: ["Intense heat", "Antioxidant", "Versatile spice"],
  },
  {
    id: "chives",
    name: "Chives",
    price: 4.99,
    category: "culinary-herbs",
    image: "https://images.unsplash.com/photo-1599440695745-e9ec50e9c0f3?w=400&q=80",
    description: "Mild onion-flavored herb perfect for garnishing and cooking.",
    ingredients: "100% dried chives",
    keyPoints: ["Mild flavor", "Versatile garnish", "Nutrient rich"],
  },
  {
    id: "goose-mint",
    name: "Goose Mint",
    price: 5.99,
    category: "culinary-herbs",
    image: "https://images.unsplash.com/photo-1628556270448-4d4e4148e1b1?w=400&q=80",
    description: "Refreshing mint variety with unique flavor profile. Great for teas and cooking.",
    ingredients: "100% dried goose mint leaves",
    keyPoints: ["Refreshing", "Digestive aid", "Aromatic"],
  },
  {
    id: "leeks",
    name: "Leeks",
    price: 6.99,
    category: "culinary-herbs",
    image: "https://images.unsplash.com/photo-1540148426945-6cf22a6b2383?w=400&q=80",
    description: "Dried leeks for soups, stews, and savory dishes. Mild onion flavor.",
    ingredients: "100% dried leeks",
    keyPoints: ["Mild flavor", "Soup base", "Nutrient dense"],
  },
  {
    id: "melisa",
    name: "Melisa",
    price: 7.99,
    category: "culinary-herbs",
    image: "https://images.unsplash.com/photo-1600857544200-b2f666a9a2ec?w=400&q=80",
    description: "Lemon balm herb with citrusy flavor. Calming and aromatic.",
    ingredients: "100% dried lemon balm",
    keyPoints: ["Lemony flavor", "Calming", "Versatile herb"],
  },
  {
    id: "moringa",
    name: "Moringa",
    price: 9.99,
    category: "culinary-herbs",
    image: "https://images.unsplash.com/photo-1611241893603-3c359704e0ee?w=400&q=80",
    description: "Superfood herb packed with nutrients. Add to smoothies, teas, or meals.",
    ingredients: "100% organic moringa leaves",
    keyPoints: ["Superfood", "High in nutrients", "Energy boost"],
  },
  {
    id: "oregano",
    name: "Oregano",
    price: 5.99,
    category: "culinary-herbs",
    image: "https://images.unsplash.com/photo-1600857544200-b2f666a9a2ec?w=400&q=80",
    description: "Mediterranean herb essential for Italian and Greek cuisine.",
    ingredients: "100% dried oregano",
    keyPoints: ["Mediterranean flavor", "Antimicrobial", "Versatile"],
  },
  {
    id: "peppermint-herb",
    name: "Pepper Mint",
    price: 5.99,
    category: "culinary-herbs",
    image: "https://images.unsplash.com/photo-1628556270448-4d4e4148e1b1?w=400&q=80",
    description: "Cool and refreshing peppermint leaves for teas and cooking.",
    ingredients: "100% dried peppermint leaves",
    keyPoints: ["Cooling", "Digestive aid", "Refreshing"],
  },
  {
    id: "rosemary",
    name: "Rosemary",
    price: 5.99,
    category: "culinary-herbs",
    image: "https://images.unsplash.com/photo-1515586000433-45406d8e6662?w=400&q=80",
    description: "Aromatic herb perfect for roasted dishes and Mediterranean cooking.",
    ingredients: "100% dried rosemary",
    keyPoints: ["Aromatic", "Memory support", "Antioxidant"],
  },
  {
    id: "sage",
    name: "Sage",
    price: 6.99,
    category: "culinary-herbs",
    image: "https://images.unsplash.com/photo-1600857544200-b2f666a9a2ec?w=400&q=80",
    description: "Earthy, savory herb for stuffings, meats, and traditional dishes.",
    ingredients: "100% dried sage leaves",
    keyPoints: ["Earthy flavor", "Brain health", "Traditional herb"],
  },
  {
    id: "savory",
    name: "Savory",
    price: 5.99,
    category: "culinary-herbs",
    image: "https://images.unsplash.com/photo-1600857544200-b2f666a9a2ec?w=400&q=80",
    description: "Peppery herb great for beans, meats, and savory dishes.",
    ingredients: "100% dried savory",
    keyPoints: ["Peppery flavor", "Bean herb", "Digestive"],
  },
  {
    id: "stinging-nettle-herb",
    name: "Stinging Nettle",
    price: 7.99,
    category: "culinary-herbs",
    image: "https://images.unsplash.com/photo-1600857544200-b2f666a9a2ec?w=400&q=80",
    description: "Nutrient-rich herb for teas, soups, and health preparations.",
    ingredients: "100% dried stinging nettle",
    keyPoints: ["Nutrient dense", "Allergy support", "Iron rich"],
  },
  {
    id: "tarragon",
    name: "Tarragon",
    price: 6.99,
    category: "culinary-herbs",
    image: "https://images.unsplash.com/photo-1600857544200-b2f666a9a2ec?w=400&q=80",
    description: "Anise-flavored herb essential for French cuisine.",
    ingredients: "100% dried tarragon",
    keyPoints: ["Anise flavor", "French cuisine", "Aromatic"],
  },
  {
    id: "thyme",
    name: "Thyme",
    price: 5.99,
    category: "culinary-herbs",
    image: "https://images.unsplash.com/photo-1600857544200-b2f666a9a2ec?w=400&q=80",
    description: "Versatile herb for soups, stews, roasts, and Mediterranean dishes.",
    ingredients: "100% dried thyme",
    keyPoints: ["Versatile", "Respiratory support", "Antiseptic"],
  },

  // Spices
  {
    id: "cardamoms",
    name: "Cardamoms",
    price: 8.99,
    category: "spices",
    image: "https://images.unsplash.com/photo-1596040033229-a9821ebd058d?w=400&q=80",
    description: "Queen of spices with sweet, aromatic flavor. Essential for chai and desserts.",
    ingredients: "100% whole cardamom pods",
    keyPoints: ["Aromatic", "Digestive aid", "Breath freshener"],
  },
  {
    id: "cinnamon",
    name: "Cinnamon",
    price: 6.99,
    category: "spices",
    image: "https://images.unsplash.com/photo-1608198093002-ad4e005f9bfe?w=400&q=80",
    description: "Sweet and warming spice for baking, beverages, and savory dishes.",
    ingredients: "100% Ceylon cinnamon",
    keyPoints: ["Blood sugar support", "Anti-inflammatory", "Warming"],
  },
  {
    id: "cloves",
    name: "Cloves",
    price: 7.99,
    category: "spices",
    image: "https://images.unsplash.com/photo-1599940824399-b87987ceb72a?w=400&q=80",
    description: "Intensely aromatic spice for baking and savory cooking.",
    ingredients: "100% whole cloves",
    keyPoints: ["Antimicrobial", "Dental health", "Warming spice"],
  },
  {
    id: "cummin-seeds",
    name: "Cummin Seeds",
    price: 5.99,
    category: "spices",
    image: "https://images.unsplash.com/photo-1596040033229-a9821ebd058d?w=400&q=80",
    description: "Earthy, warming spice essential for Indian and Middle Eastern cuisine.",
    ingredients: "100% cumin seeds",
    keyPoints: ["Earthy flavor", "Digestive aid", "Iron rich"],
  },
  {
    id: "dill-seeds",
    name: "Dill Seeds",
    price: 5.99,
    category: "spices",
    image: "https://images.unsplash.com/photo-1596040033229-a9821ebd058d?w=400&q=80",
    description: "Caraway-like flavor perfect for pickles, breads, and fish dishes.",
    ingredients: "100% dill seeds",
    keyPoints: ["Pickling essential", "Digestive", "Mild flavor"],
  },
  {
    id: "fennel-seeds",
    name: "Fennel Seeds",
    price: 5.99,
    category: "spices",
    image: "https://images.unsplash.com/photo-1596040033229-a9821ebd058d?w=400&q=80",
    description: "Sweet, licorice-flavored seeds for cooking and digestive health.",
    ingredients: "100% fennel seeds",
    keyPoints: ["Sweet flavor", "Digestive aid", "Breath freshener"],
  },
  {
    id: "fenugreek",
    name: "Fenugreek",
    price: 6.99,
    category: "spices",
    image: "https://images.unsplash.com/photo-1596040033229-a9821ebd058d?w=400&q=80",
    description: "Slightly bitter spice with maple-like aroma. Used in curries and health preparations.",
    ingredients: "100% fenugreek seeds",
    keyPoints: ["Blood sugar support", "Lactation aid", "Unique flavor"],
  },
  {
    id: "ginger",
    name: "Ginger",
    price: 6.99,
    category: "spices",
    image: "https://images.unsplash.com/photo-1615485500704-8e990f9900f7?w=400&q=80",
    description: "Warming, zesty spice for cooking, baking, and health remedies.",
    ingredients: "100% dried ginger root",
    keyPoints: ["Anti-nausea", "Anti-inflammatory", "Warming"],
  },

  // Seasonings
  {
    id: "chili-powder",
    name: "Chili Powder",
    price: 5.99,
    category: "seasonings",
    image: "https://images.unsplash.com/photo-1583119022894-919a68a3d0e3?w=400&q=80",
    description: "Versatile spice blend adding heat and color to any dish.",
    ingredients: "Ground dried chillies",
    keyPoints: ["Adds heat", "Rich color", "Vitamin C"],
  },
  {
    id: "chilli-seasoning",
    name: "Chilli Seasoning",
    price: 6.99,
    category: "seasonings",
    image: "https://images.unsplash.com/photo-1583119022894-919a68a3d0e3?w=400&q=80",
    description: "Complete seasoning blend for chilli con carne and spicy dishes.",
    ingredients: "Chilli, Cumin, Garlic, Oregano, Paprika",
    keyPoints: ["Complete blend", "Mexican cuisine", "Versatile"],
  },
  {
    id: "lemon-seasoning",
    name: "Lemon Seasoning",
    price: 5.99,
    category: "seasonings",
    image: "https://images.unsplash.com/photo-1596040033229-a9821ebd058d?w=400&q=80",
    description: "Bright, citrusy blend for fish, chicken, and vegetables.",
    ingredients: "Lemon zest, Herbs, Sea salt, Pepper",
    keyPoints: ["Citrus fresh", "Versatile", "Low sodium option"],
  },
  {
    id: "meat-seasoning",
    name: "Meat Seasoning",
    price: 6.99,
    category: "seasonings",
    image: "https://images.unsplash.com/photo-1596040033229-a9821ebd058d?w=400&q=80",
    description: "Savory blend perfect for grilling, roasting, and braising meats.",
    ingredients: "Salt, Pepper, Garlic, Onion, Herbs",
    keyPoints: ["Perfect for meats", "Balanced flavor", "Grill essential"],
  },
  {
    id: "soup-mix",
    name: "Soup Mix",
    price: 7.99,
    category: "seasonings",
    image: "https://images.unsplash.com/photo-1596040033229-a9821ebd058d?w=400&q=80",
    description: "Complete seasoning for homemade soups and stews.",
    ingredients: "Dried vegetables, Herbs, Spices",
    keyPoints: ["Soup base", "Convenient", "Flavorful"],
  },

  // Coffee
  {
    id: "green-coffee",
    name: "Green Coffee",
    price: 12.99,
    category: "coffee",
    image: "https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?w=400&q=80",
    description: "Unroasted coffee beans for home roasting or health beverages. High in chlorogenic acid.",
    ingredients: "100% green coffee beans",
    keyPoints: ["Weight management", "Antioxidant", "Home roasting"],
  },
  {
    id: "parchment-coffee",
    name: "Parchment Coffee",
    price: 11.99,
    category: "coffee",
    image: "https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?w=400&q=80",
    description: "Coffee with parchment intact for optimal freshness and storage.",
    ingredients: "100% parchment coffee beans",
    keyPoints: ["Fresh storage", "Traditional", "Quality beans"],
  },
  {
    id: "mild-roast-coffee",
    name: "Mild Roast Coffee",
    price: 13.99,
    category: "coffee",
    image: "https://images.unsplash.com/photo-1559056199-641a0ac8b55e?w=400&q=80",
    description: "Light roast with bright, fruity notes. Higher caffeine content.",
    ingredients: "100% Arabica beans, light roast",
    keyPoints: ["Fruity notes", "Higher caffeine", "Smooth flavor"],
  },
  {
    id: "medium-roast-coffee",
    name: "Medium Roast Coffee",
    price: 13.99,
    category: "coffee",
    image: "https://images.unsplash.com/photo-1559056199-641a0ac8b55e?w=400&q=80",
    description: "Balanced roast with caramel notes. Perfect everyday coffee.",
    ingredients: "100% Arabica beans, medium roast",
    keyPoints: ["Balanced flavor", "Caramel notes", "Versatile"],
  },
  {
    id: "hard-roast-coffee",
    name: "Hard Roast Coffee",
    price: 13.99,
    category: "coffee",
    image: "https://images.unsplash.com/photo-1559056199-641a0ac8b55e?w=400&q=80",
    description: "Dark roast with bold, smoky flavor. Lower caffeine, rich taste.",
    ingredients: "100% Arabica beans, dark roast",
    keyPoints: ["Bold flavor", "Smoky notes", "Rich aroma"],
  },

  // Seeds
  {
    id: "alfalfa-seeds",
    name: "Alfalfa Seeds",
    price: 8.99,
    category: "seeds",
    image: "https://images.unsplash.com/photo-1591857177580-dc82b9ac4e1e?w=400&q=80",
    description: "Sprouting seeds for fresh, nutritious sprouts. Rich in vitamins.",
    ingredients: "100% organic alfalfa seeds",
    keyPoints: ["Easy sprouting", "Nutrient dense", "Fresh greens"],
  },
  {
    id: "avocado-seeds",
    name: "Avocado Seeds",
    price: 9.99,
    category: "seeds",
    image: "https://images.unsplash.com/photo-1591857177580-dc82b9ac4e1e?w=400&q=80",
    description: "For growing your own avocado trees. Includes planting instructions.",
    ingredients: "Fresh avocado seeds",
    keyPoints: ["Grow your own", "Educational", "Sustainable"],
  },
  {
    id: "blackberry-seeds",
    name: "Blackberry Seeds",
    price: 7.99,
    category: "seeds",
    image: "https://images.unsplash.com/photo-1591857177580-dc82b9ac4e1e?w=400&q=80",
    description: "Plant seeds for growing blackberry bushes in your garden.",
    ingredients: "Blackberry plant seeds",
    keyPoints: ["Fruit growing", "Garden starter", "Perennial"],
  },
  {
    id: "sage-seeds",
    name: "Sage Seeds",
    price: 6.99,
    category: "seeds",
    image: "https://images.unsplash.com/photo-1591857177580-dc82b9ac4e1e?w=400&q=80",
    description: "Grow your own sage herb garden with these quality seeds.",
    ingredients: "Salvia officinalis seeds",
    keyPoints: ["Herb garden", "Easy growing", "Medicinal herb"],
  },
  {
    id: "purple-tea-seeds",
    name: "Purple Tea Seeds",
    price: 12.99,
    category: "seeds",
    image: "https://images.unsplash.com/photo-1591857177580-dc82b9ac4e1e?w=400&q=80",
    description: "Rare purple tea plant seeds for dedicated gardeners.",
    ingredients: "Camellia sinensis (purple variety) seeds",
    keyPoints: ["Rare variety", "Tea garden", "Specialty plant"],
  },
]

export const categories = [
  { id: "all", name: "All Products" },
  { id: "healing-teas", name: "Healing Teas" },
  { id: "green-teas", name: "Green Teas" },
  { id: "culinary-herbs", name: "Culinary Herbs" },
  { id: "spices", name: "Spices" },
  { id: "seasonings", name: "Seasonings" },
  { id: "coffee", name: "Coffee" },
  { id: "seeds", name: "Seeds" },
]

export const medicalPlants = [
  "Ajuga Remota",
  "Artemisia annua",
  "Avocado",
  "California Poppy",
  "Celery",
  "Chamomile",
  "Chayote",
  "Cilantro",
  "Comfrey",
  "Dill seeds",
  "Eucalyptus",
  "Fennel seeds",
  "Fenugreek",
  "Feverfew",
  "Goose mint",
  "Lancelot Minor",
  "Lavender",
  "Lemon grass",
  "Loquat",
  "Madagascan Periwinkle",
  "Melisa",
  "Mexican bush sage",
  "Milk Thistle",
  "Muigoya",
  "Oregano",
  "Ox eye daisy",
  "Parsley",
  "Passion fruit",
  "Pepper mint",
  "Plantago Major",
  "Plantago minor",
  "Prunus Africana",
  "Rosemary",
  "Sage salvia",
  "Scented-Leaf Geraniums",
  "Spearmint",
  "Stinging nettle",
  "Thyme",
  "Warburgia UG",
]
